### ISSUE TITLE
Sailfish OS въ раздѣлѣ мобильныхъ операціонныхъ системъ

### ISSUE THREAD

**Issue by steils** [c0rdis/privacytools.ru#18]
Весьма удивленъ присутствіемъ Sailfish OS на privacytools.{io,ru}, хотя самъ пользователь этой операціонной системы. Во-первыхъ, словами «Преимущественно открытая операционная система» можно описать и обычный Android, но его же вы въ списокъ не включаете. Sailfish — хорошая операціонная система, но непонятно, насколько хороша въ приватности и защитѣ пользовательскихъ данныхъ. Въ томъ числѣ, потому что она частично закрыта. Въ томъ числѣ полностью закрытъ Alien Dalvik, при этомъ нѣтъ возможности настраивать разрѣшенія для приложеній, какъ въ собственно Android'ѣ.
Но больше всего удивила ссылка на https://habr.com/post/410177/. То есть ссылка на дѣятельность Ростелекома, господа, при томъ, что сайтъ разсказываетъ о правительственныхъ слѣжкахъ.

Я бы удалилъ вообще этотъ пунктъ изъ списка. Или, по крайней мѣрѣ, можно сдѣлать, какъ въ англійской версіи, ясное уточненіе, что есть «proprietary UI contributed by Jolla, and other third-party components». И либо удалить странную ссылку на новость про Ростелекомъ, либо пояснить, что это именно то, чего стоитъ опасаться въ работѣ съ этой системой.

**Comment by c0rdis** [comment]
Глубокоуважаемый @steils,
премного благодарен за рекомендацию и приношу свои искренние извинения в связи с вынужденно долгим ответом. Ваше предложение рассмотрено и полностью удовлетворено, Sailfish более не отображается в списке систем. Прошу Вас и впредь помогать нам полезными советами.
