### ISSUE TITLE
Устарелая информация, предложение, вопрос

### ISSUE THREAD

**Issue by testuser51** [c0rdis/privacytools.ru#19]
### Устарелая информация:
1. Поисковые системы — См. Также — findx - открытый исходный код. Без сбора логов и отслеживания. Прозрачность алгоритмов. Сделано в Европе. 

Findx погиб. F в чат, парни.

2. Альтернативы email — I2P-Bote.

Я не знаю что это за сайт, но он не работает. Возможно, временно.

### Предложение: 
1. Рассказать про альтернативы Microsoft Office.

Например, LibreOffice.

2. Рассказать про https://send.firefox.com

### Вопрос:
1. Почему нигде не рассказывается про Telegram? Хороший мессенжер.

**Comment by testuser51** [comment]
Кстати, очень много информации на одной странице. 

Заходишь, а тебе в лицо про законы, "свидетельство канарейки", статистика.

Надо сделать как в английской версии сайта: краткое описание и "читать больше". Там всё опрятно и просто.

**Comment by digitalkiller** [comment]
Русскоязычная версия сайта очень давно не обновлялась (последний коммит был 1 января), поэтому так много информации на одной странице и давным давно устаревшая информация. Кстати, отвечу на первый вопрос: Telegram сам по себе не самый лучший приватный месседжер, даже если присмотреться на варианты на англоязычной версии, то Telegram ты там не найдёшь. Даже не знаю, что с этим сайтом делать, столько устаревшей информации...

**Comment by testuser51** [comment]
> столько устаревшей информации

Надо указать и ждать, я думаю.

**Comment by digitalkiller** [comment]
Боюсь, что владельцу придётся делать форк заново, так как оригинал давно перешёл на Jekyll. Без Jekyll делать страницы очень сложно, поверьте мне. Пыталась связаться с ним на Reddit, ответа пока что нет.

**Comment by c0rdis** [comment]
Привет, спасибо за комментарии! К сожалению, действительно в последнее время не было возможности регулярно обновлять страницу. Не хотите присоединиться как контрибуторы / приготовить pull requests на уже существующие материалы? Думаю, вместе дело пойдет веселее :)

**Comment by digitalkiller** [comment]
@c0rdis Конечно, я могу присоединиться как контрибутор :wink:
